CREATE TABLE IF NOT EXISTS support_posts (
    id SERIAL NOT NULL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    title TEXT NOT NULL,
    comment TEXT NOT NULL,
    email TEXT NOT NULL
)